2023-04-16 13:55:18,914 luigi[83164] INFO: logging configured by default settings
2023-04-16 13:55:18,915 luigi.scheduler[83164] INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with empty state
2023-04-16 13:55:18,919 luigi.server[83164] INFO: Scheduler starting up
2023-04-16 13:56:02,851 luigi[83221] INFO: logging configured by default settings
2023-04-16 13:56:02,852 luigi.scheduler[83221] INFO: No prior state file exists at /var/lib/luigi-server/state.pickle. Starting with empty state
Traceback (most recent call last):
  File "/Users/bhavyashukla/opt/anaconda3/bin/luigid", line 8, in <module>
    sys.exit(luigid())
  File "/Users/bhavyashukla/opt/anaconda3/lib/python3.9/site-packages/luigi/cmdline.py", line 37, in luigid
    luigi.server.run(api_port=opts.port, address=opts.address, unix_socket=opts.unix_socket)
  File "/Users/bhavyashukla/opt/anaconda3/lib/python3.9/site-packages/luigi/server.py", line 347, in run
    _init_api(
  File "/Users/bhavyashukla/opt/anaconda3/lib/python3.9/site-packages/luigi/server.py", line 329, in _init_api
    api_sockets = tornado.netutil.bind_sockets(api_port, address=address)
  File "/Users/bhavyashukla/opt/anaconda3/lib/python3.9/site-packages/tornado/netutil.py", line 161, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
